### ISSUE TITLE
Phonebook & contacts icons

### ISSUE THREAD

**Issue by Studio384** [optimise-group/valkyrie#13]
Related to optimise-group/meili#84

Valkyrie 0.7 should include a new set of icons related to the contacts and phonebook features. Below is a (currently) partial list of the suggested icons and alterations to existing icons:

- [x] `address-book`
- [x] `id-card`: updated to match other user-icon glyphs. Can be used for individual contacts.
- [x] `contact-groups`, see `users`.
- [x] `phone`: update icon to better match the scale of the other icons.
- [x] `filter`
- [x] `filter-plus`
- [x] `filter-x-mark`

**Comment by timothyvanderaerden** [comment]
Maybe it's also useful to have the following?

- (contact) Groups
- Different types of phone number icons (home, mobile, work, fax, other)

**Comment by Studio384** [comment]
We already have the appropriate icons for the various types availeble (where "Other" will be represented by the normal `phone`-icon).

![image](https://user-images.githubusercontent.com/1693592/129350574-763024e7-51dd-4564-8285-eb63d328fc33.png)

I've added contact groups to the list.
